name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move files from public to root
        run: |
          mkdir -p public-root
          cp -r public/* public-root/
          mv public-root/* .

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .
          token: ${{ secrets.GH_TOKEN }}
